version: '3'
services:
  orchestrator:
    image: "porbs/df:orchestrator"
    ports:
      - "3000:3000"
  worker1:
    image: "porbs/df:worker"
    ports:
        - "3001:3000"
  worker2:
    image: "porbs/df:worker"
    ports:
        - "3002:3000"
  worker3:
    image: "porbs/df:worker"
    ports:
        - "3003:3000"
